// This file is auto-generated by @hey-api/openapi-ts

export type GetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type GetResponses = {
  /**
   * Default Response
   */
  200: unknown;
};

export type ClientOptions = {
  baseUrl: `${string}://openapi.yml` | (string & {});
};
